"""add user_id to Reservations

Revision ID: c819e9c5b39b
Revises: 
Create Date: 2026-08-05 16:26:16.606534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c819e9c5b39b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Reservations', sa.Column('user_id', sa.Integer(), nullable=False))
    op.add_column('Reservations', sa.Column('department', sa.String(), nullable=False))
    op.add_column('Reservations', sa.Column('symptoms', sa.String(), nullable=False))
    op.add_column('Reservations', sa.Column('reservation_time', sa.DateTime(timezone=True), nullable=False))
    op.add_column('Reservations', sa.Column('status', sa.Enum('pending', 'confirmed', 'canceled', name='reservationstatus'), nullable=False))
    op.add_column('Reservations', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
    op.create_foreign_key(None, 'Reservations', 'Users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Reservations', type_='foreignkey')
    op.drop_column('Reservations', 'created_at')
    op.drop_column('Reservations', 'status')
    op.drop_column('Reservations', 'reservation_time')
    op.drop_column('Reservations', 'symptoms')
    op.drop_column('Reservations', 'department')
    op.drop_column('Reservations', 'user_id')
    # ### end Alembic commands ###
